name: RimskayaFotostudia
favicon: null
layout_spectrum: 0.92619
typography_spectrum: 0.89541
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.022752256831154227
  rhythmicContrast: 0.25
purpose: []
