name: RimskayaFotostudia
favicon: null
layout_spectrum: 0.92619
typography_spectrum: 0.89541
title: Rimskaya Masterskaya Fotografii v Kharkove
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d2d5cf'
    - '#313735'
    - '#00647d'
    - '#835d41'
    - '#bf8450'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.022752256831154227
  rhythmicContrast: 0.25
purpose: []
